// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBek8ugqDYdNEjRQKCw5mfqP9vRrBS8TZE',
    appId: '1:580162992218:web:13388a0353269f24498063',
    messagingSenderId: '580162992218',
    projectId: 'fixit-lanka',
    authDomain: 'fixit-lanka.firebaseapp.com',
    storageBucket: 'fixit-lanka.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_59mH821wywfDnY6xZ8_cfG_5M4EwtsM',
    appId: '1:580162992218:android:67ac872da499fff0498063',
    messagingSenderId: '580162992218',
    projectId: 'fixit-lanka',
    storageBucket: 'fixit-lanka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwy4mqxTruX7z4sfn8usS19rlHCIpxQTo',
    appId: '1:580162992218:ios:1b0d621b7a956e1c498063',
    messagingSenderId: '580162992218',
    projectId: 'fixit-lanka',
    storageBucket: 'fixit-lanka.firebasestorage.app',
    iosBundleId: 'com.example.workerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwy4mqxTruX7z4sfn8usS19rlHCIpxQTo',
    appId: '1:580162992218:ios:1b0d621b7a956e1c498063',
    messagingSenderId: '580162992218',
    projectId: 'fixit-lanka',
    storageBucket: 'fixit-lanka.firebasestorage.app',
    iosBundleId: 'com.example.workerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBek8ugqDYdNEjRQKCw5mfqP9vRrBS8TZE',
    appId: '1:580162992218:web:212630aa87f8202a498063',
    messagingSenderId: '580162992218',
    projectId: 'fixit-lanka',
    authDomain: 'fixit-lanka.firebaseapp.com',
    storageBucket: 'fixit-lanka.firebasestorage.app',
  );
}
